
name: CI

on:
  push:
    branches: 
    - master
    - fmt-ci
  pull_request:
    branches:
    - master
    - fmt-ci

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo build
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features -- -D warnings